config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'contests#index'
  get "learn" => "static_pages#learn"

  get "users" => "users#index", as: "users"
  get "users/:id" => "users#show", as: "user"

  resources :gamesets
  resources :games
  resources :teams
  resources :game_gameset_relationships

  resources :contests do
    get 'entries', on: :member
  end

end

app/models/gameset.rb
class Gameset < ActiveRecord::Base
	has_many :game_gameset_relationships
	has_many :games, through: :game_gameset_relationships
	has_many :contests
	belongs_to :user

	def eastern_time
		starttime.advance(:hours => -5)
	end

end

app/controllers/gamesets_controller.rb
class GamesetsController < ApplicationController
  before_action :set_return, only: [:show, :edit, :update, :destroy]

  def index
    @gamesets = Gameset.all
  end

  def show
    @gameset = Gameset.find(params[:id])
  end

  def new
    @gameset = Gameset.new
  end

  def edit
    @gameset = Gameset.find(params[:id])
  end

  def create
  @return = Gameset.new(return_params)
    if @return.save
      redirect_to @return, notice: 'Gameset was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @return.update(return_params)
      redirect_to @return, notice: 'Gameset was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
  @return.destroy
    redirect_to returns_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_return
      @return = Gameset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def return_params
      params.require(:gameset).permit(:user_id, :league, :name, :starttime, :game_id, :game_ids => [])
    end
end

app/views/gamesets/_form.html.erb
<%= form_for(@gameset) do |f| %>
  <% if @gameset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gameset.errors.count, "error") %> prohibited this gameset from being saved:</h2>

      <ul>
      <% @gameset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :league %><br>
    <%= f.select :league, collection: ['MLB'] %>
  </div>

  <div class="form-group">
    <%= f.label :gameset_name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :starttime %><br>
    <%= f.datetime_select :starttime %>
  </div>

  <div class="form-group">
    <%= f.label :game_id %><br>
    <%= collection_check_boxes :gameset, :game_ids, Game.all, :id, :name %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>

<% end %>

app/views/gamesets/edit.html.erb
<h1>Editing gameset</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @gameset, class: 'btn btn-warning' %>

<br><br>

<%= link_to 'Back to Gamesets', gamesets_path, class: 'btn btn-info' %>

app/views/gamesets/index.html.erb
<h1>Gamesets</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>League</th>
      <th>Name</th>
      <th>Start Time</th>
      <th>Games</th>
      <th># of Games</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gamesets.each do |gameset| %>
      <tr>
        <td><%= gameset.id %></td>
        <td><%= gameset.league %></td>
        <td><%= gameset.name %></td>
        <td><%= gameset.starttime %></td>
        <td><% gameset.games.each do |game| %>
              <%= game.name %><br>
            <% end %>
        </td>
        <td><%= gameset.games.count %></td>
        <td><%= link_to 'Edit', edit_gameset_path(gameset) %></td>
        <td><%= link_to 'Show', gameset %></td>
        <td><%= link_to 'Remove', gameset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gameset', new_gameset_path, class: 'btn btn-warning' %>

app/views/gamesets/new.html.erb
<h1>New gameset</h1>

<%= render 'form' %>

<%= link_to 'Back', gamesets_path %>

app/views/gamesets/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @gameset.name %></h1>

<p>
  <strong>League:</strong>
  <%= @gameset.league %>
</p>

<p>
  <strong>Gameset Start Time:</strong>
  <%= @gameset.eastern_time.strftime("%a %b %d %I:%M %p EST") %>
</p>

<p>
  <strong>Number of Games:</strong>
  <%= @gameset.games.count %>
 </p>

<table class="table">
  <thead>
    <tr>
      <th>Away</th>
      <th>Home</th>
      <th>Start Time</th>       
    </tr>
  </thead>
    <tbody>
      <tr>
      <% @gameset.games.order("id ASC").each do |game| %>
        <td><%= game.away_team.full_team_name %></td>
        <td><%= game.home_team.full_team_name %></td>
        <td><%= game.starttime.advance(:hours => -5).strftime("%a %b %d %I:%M %p EST") %></td>
      <tr>
      <% end %>
    <tbody>
</table>    
 


<%= link_to 'Back to Gamesets', gamesets_path, class: 'btn btn-info btn-sm' %>
<br><br>
<%= link_to 'Edit', edit_gameset_path(@gameset), class: 'btn btn-danger btn-sm' %>
<br><br>
<%= link_to 'New Gameset', new_gameset_path, class: 'btn btn-warning btn-sm'%>
<br><br>
<%= link_to 'Back to Contests', contests_path, class: 'btn btn-info btn-sm' %>