config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'contests#index'
  get "learn" => "static_pages#learn"

  get "users" => "users#index", as: "users"
  get "users/:id" => "users#show", as: "user"

  resources :gamesets
  resources :games
  resources :teams
  resources :game_gameset_relationships

  resources :contests do
    get 'entries', on: :member
  end

end

app/models/contest.rb
class Contest < ActiveRecord::Base
	belongs_to :user
	belongs_to :gameset

	has_many :games, through: :gameset
	has_many :entries, dependent: :destroy
	has_many :users, through: :entries

	accepts_nested_attributes_for :games

 	def winner_id
 		@winner = entries.detect { |entry| entry.entry_sum == entries.map(&:entry_sum).max }
 		@winner.id
 	end

  	def winner_username
 		@winner = entries.detect { |entry| entry.entry_sum == entries.map(&:entry_sum).max }
 		@winner.user.username
 	end

	def eastern_time
		starttime.advance(:hours => -5)
	end

	def entries
		Entry.where(contest_id: id).order(:game_id).all
	end

	def contest_users
		Entry.uniq.pluck(:user_id)
	end

	validates :league, :gameset_id, :name, :starttime, presence: true
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]
  #before_action :correct_user, only: [:edit, :update, :destroy]
  #before_action :authenticate_user!, except: [:index, :show]

  def index
    @contests = Contest.all
  end

  def show
    @contest = Contest.find(params[:id])
    @entries = Entry.where(contest_id: @contest.id, user_id: current_user).all
  end

  def new
    @contest = Contest.new
  end

  def edit
  end

  def create
    @contest = Contest.new(contest_params)
    @contest.starttime = @contest.gameset.starttime
    if @contest.save
      redirect_to @contest, notice: 'Contest was successfully created.'
    else
      render action: 'new'
    end
  end


  def update
    if @contest.update(contest_params)
      redirect_to @contest, notice: 'Contest was successfully updated.'
    else
      render action: 'edit'
    end
  end


  def destroy
    @contest.destroy
    redirect_to contests_url
  end

  def entries
    @users = User.where(id: current_user)
    @contest = Contest.find(params[:id])
    @games = @contest.games
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    def correct_user
      @contest = current_user.contests.find_by(id: params[:id])
      redirect_to contests_path, notice: "Not authorized to edit this contest" if @contest.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:user_id, 
                                    :league, 
                                    :name, 
                                    :gameset_id,
                                    :size,  
                                    :starttime, 
                                    :game_id, 
                                    :game_ids => [], 
                                    :games_attributes => [:id, :name,
                                    :entries_attributes => [:id, :user_id, :game_id, :weight, :selected_winner_id, :contest_id]
                                    ])
    end
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :league %><br>
    <%= f.select :league, collection: ['MLB'] %>
  </div>

  <div class="form-group">
    <%= f.label :name, 'Name Your Contest' %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :gameset_id, 'Select Gameset' %>
    <%= f.collection_select(:gameset_id, Gameset.all, :id, :name, { :prompt => true } ) %>
  </div>
  
  <div class="form-group">
    <%= f.label :size, 'How many opponents can enter your contest?' %><br>
    <%= f.number_field :size, class: "form-control form-number" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @survey, class: 'btn btn-warning' %>

<br><br>

<%= link_to 'Back to Contests', contests_path, class: 'btn btn-info' %>

app/views/contests/entries.html.erb
<%= form_for(@contest) do |f| %>
  <% @users.each do |user| %>
  <h3><%= user.email %></h3>
  <table>
    <thead>
      <tr>
        <td>Home Team</td>
        <td>Away Team</td>
        <td>Selected Winner</td>
        <td>Weight</td>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
      <tr>
        <td><%= game.home_team.full_team_name %></td>
        <td><%= game.away_team.full_team_name %></td>
        <td>
        <%= f.fields_for :games, game do |g| %>
          <%= g.fields_for :entries, game.entries.where(user: user, contest: @contest.id).first_or_initialize do |e| %>
            <%= e.select :selected_winner_id, options_for_select({game.away_team.full_team_name => game.away_team.id, game.home_team.full_team_name => game.home_team.id}), { :prompt => true }%>
            <%= e.number_field :weight %>
            <%= e.hidden_field :user_id, :value => current_user.id %>
            <%= e.hidden_field :contest_id, :value => @contest.id %>
          <% end %>
        <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/contests/index.html.erb
<% if user_signed_in? %>
<ul class="nav nav-tabs">
  <li class="active"><a href="#">All</a></li>
  <li><a href="#">NFL</a></li>
  <li><a href="#">NBA</a></li>
  <li><a href="#">MLB</a></li>
  <li><a href="#">NHL</a></li>
</ul>
  <p>
    <%= link_to "Create New Contest", new_contest_path, class: 'btn btn-warning btn-entry btn-sm' %>
  </p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>League</th>
          <th>Contest Name</th>
          <th>Matchset</th>
          <th>Start Time</th>
          <th>Contest Size</th>
          <th>Users entered</th>
        </tr>
      </thead>
      <tbody>
        <% @contests.each do |contest| %>
        <tr>
          <td><%= contest.league %></td>
          <td><%= link_to contest.name, contest %></td>
          <td><%= link_to contest.gameset.name, gameset_path(contest.gameset_id) %></td>
          <td><%= contest.starttime.advance(:hours => -5).strftime("%a %b %d %I:%M %p EST") %></td>
          <td><%= contest.size %></td>
          <td><%= contest.users.uniq.each.count %></td>
        </tr>
        <% end %>
      </tbody>
  </table>
<% else %>
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to BallerCallers</h1>
    <p class="center">New to BallerCallers? <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary"  %></p>
    <p class="center">Not sure how to play? <%= link_to "Learn here", learn_path, class: "btn btn-primary" %></p>
    <p class="center">Already ballin'? <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary"  %></p>
  </div>
</div>
<% end %>

app/views/contests/new.html.erb
<h1>Create a new contest</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', contests_path, class: 'btn btn-info btn-sm' %>

app/views/contests/show.html.erb
<h1><%= @contest.name %></h1>

<p>
  <strong>League:</strong>
  <%= @contest.league %>
</p>

<p>
  <strong>Matchset:</strong>
  <%= @contest.gameset.name %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @contest.starttime.advance(:hours => -5).strftime("%a %b %d %I:%M %p EST") %>
</p>

 <p>
  <strong>Number of Games:</strong>
  <%= @contest.games.count %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="3">Games</th>
      <th>Start Time</th>     
    </tr>
  </thead>
    <tbody>
      <tr>
      <% @contest.games.order('id').each do |game| %>
        <td><%= game.away_team.full_team_name %> @ <%= game.home_team.full_team_name %></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td><%= game.starttime.advance(:hours => -5).strftime("%a %b %d %I:%M %p EST") %></td>
      </tr>
      <% end %>
    </tbody>
</table>

<br>

<p>
  <strong>Contest Size:</strong>
  <%= @contest.size %>
</p>

<p>
  <strong>Users Entered:</strong>
  <%= @contest.users.uniq.each.count %>
  <% @contest.users.uniq.each do |u| %>
  <br>
  <%= u.email %>
  <%= u.score_test %>
  <% end %>
</p>

<% if @entries.empty? %>
  <h1> You have not entered this contest yet. Click below to Enter.</h1>
<% else %>
  <p><strong>Your Entry:</strong></p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Game</th>
          <th>Selected Winner</th>
          <th>Weight</th>
          <th>Actual Winner</th>
          <th>Points</th>
        </tr>
      </thead>
      <tbody>
        <tr> 
          <% @entries.each do |e| %>
          <td><%= e.game.away_team.full_team_name %> @ <%= e.game.home_team.full_team_name %></td> 
          <td><%= e.selected_winner.full_team_name %></td>
          <td><%= e.weight %></td>
          <% if e.game.status == "Ended" %>
            <td><%= e.game.winning_team.full_team_name %>
            <td><% if e.game.winning_team == e.selected_winner%><strong><%= e.weight %></strong><% else %><% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

<% end %>

<% if Time.now < @contest.starttime %>
  <%= link_to 'Enter This Contest', entries_contest_path(@contest, :contest_id => @contest.id), class: 'btn btn-success btn-sm' %>
<% else %>
  <h2>This contest is either in progress or has ended and you can no longer join. Sorry, bud.</h2>
<% end %>

<br><br>
<%= link_to 'Back to Contests', contests_path, class: 'btn btn-info btn-sm' %>

<br><br><br><br>


<%= link_to 'Edit Contest', edit_contest_path(@contest), class: 'btn btn-warning btn-xs' %>
      