config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'contests#index'
  get "learn" => "static_pages#learn"

  get "users" => "users#index", as: "users"
  get "users/:id" => "users#show", as: "user"

  resources :gamesets
  resources :games
  resources :teams
  resources :game_gameset_relationships

  resources :contests do
    get 'entries', on: :member
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
	<%= link_to "BallerCallers", root_path, id: "logo" %>
	<nav>
	  <ul class="nav navbar-nav navbar-right">
	  	<li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin</a>
          <ul class="dropdown-menu">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Learn",   learn_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Teams", teams_path %></li>
            <li><%= link_to "Games", games_path %></li>
            <li><%= link_to "Gamesets", gamesets_path %></li>
          </ul>
      </li>
		<% if user_signed_in? %>
			<li><%= link_to "My Account", edit_user_registration_path %></li>  
    <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
		<% else %>
			<li><%= link_to "Sign In", new_user_registration_path %></li>
		<% end %>
	  </ul>
	</nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>BallerCallers</title>
	<%= stylesheet_link_tag 'application', media: 'all',
										   'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
	  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	  </script>
	<![endif]-->
  </head>
	<body>
		<%= render 'layouts/header' %>
		<div class ="container">
			<% if notice %>
				<div class="container center">
					<p class="alert alert-success"><%= notice %></p>
				</div>
			<% end %>

			<% if alert %>
				<div class="container center">
		  		<p class="alert alert-success"><%= alert %></p>
		  	</div>
		  <% end %>	 

			<%= yield %>

			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>